# .github/workflows/ci.yml
name: CI
on:
  pull_request:
  push:
    branches: [ main, develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install SDK dependencies
        run: |
          if [ -f sdk/template_agent/requirements.txt ]; then
            pip install -r sdk/template_agent/requirements.txt
          fi
          pip install pytest

      - name: Run SDK tests
        run: |
          if [ -d sdk/template_agent/tests ]; then
            pytest -q sdk/template_agent/tests || exit 1
          else
            echo "No tests found, skipping."
          fi

      - name: Validate repository structure
        run: |
          test -f node_runtime/connector.js
          test -f node_runtime/installation_script.sh
          test -f api/specification.md
          echo "Structure OK"
